<HTML>
<HEAD>
    <TITLE>Law Kanoon</TITLE>
    <META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=UTF-8">
    <meta name="keywords" content="law, kanoon, kanun, kanon, indian, justice, order, court, lawyer">
    <meta name="description" content="Information on indian law and order">
    <LINK HREF="style.css" TYPE="text/css" REL="stylesheet">

    <script>

        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
            (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

        ga('create', 'UA-62794789-1', 'auto');
        ga('send', 'pageview');
        function MM_swapImgRestore() { //v3.0
            var i, x, a = document.MM_sr;
            for (i = 0; a && i < a.length && (x = a[i]) && x.oSrc; i++) x.src = x.oSrc;
        }

        function MM_preloadImages() { //v3.0
            var d = document;
            if (d.images) {
                if (!d.MM_p) d.MM_p = new Array();
                var i, j = d.MM_p.length, a = MM_preloadImages.arguments;
                for (i = 0; i < a.length; i++)
                    if (a[i].indexOf("#") != 0) {
                        d.MM_p[j] = new Image;
                        d.MM_p[j++].src = a[i];
                    }
            }
        }

        function MM_findObj(n, d) { //v4.01
            var p, i, x;
            if (!d) d = document;
            if ((p = n.indexOf("?")) > 0 && parent.frames.length) {
                d = parent.frames[n.substring(p + 1)].document;
                n = n.substring(0, p);
            }
            if (!(x = d[n]) && d.all) x = d.all[n];
            for (i = 0; !x && i < d.forms.length; i++) x = d.forms[i][n];
            for (i = 0; !x && d.layers && i < d.layers.length; i++) x = MM_findObj(n, d.layers[i].document);
            if (!x && d.getElementById) x = d.getElementById(n);
            return x;
        }

        function MM_swapImage() { //v3.0
            var i, j = 0, x, a = MM_swapImage.arguments;
            document.MM_sr = new Array;
            for (i = 0; i < (a.length - 2); i += 3)
                if ((x = MM_findObj(a[i])) != null) {
                    document.MM_sr[j++] = x;
                    if (!x.oSrc) x.oSrc = x.src;
                    x.src = a[i + 2];
                }
        }
    </script>




</HEAD>
<BODY BGCOLOR=#FFFFFF LEFTMARGIN=0 TOPMARGIN=0 rightmargin="0" bottommargin="0" MARGINWIDTH=0 MARGINHEIGHT=0
      onLoad="MM_preloadImages('images/m11.jpg','images/m21.jpg','images/m31.jpg','images/m41.jpg','images/m51.jpg')" onresize="changeImage();" >
<script type="text/javascript">
    <!-- Hide Javascript
    function changeImage(){
        document.getElementById("banner1").style.height="75%";
        document.getElementById("banner1").style.height="75%";
        return true;
    }

    -->
</script>

<script src="change_color.js"></script>
<h3 id="jstest" onmouseover="changeColor();" onmouseout= "changeAgain();">Rollover!! </h3>
<center>
    <TABLE WIDTH=712 id="banner1" BORDER=0 CELLPADDING=0 CELLSPACING=0>
        <TR>
            <TD>
                <TABLE WIDTH=712 BORDER=0 CELLPADDING=0 CELLSPACING=0>
                    <TR>
                        <TD><IMG SRC="images/spacer.gif" WIDTH=712 HEIGHT=21 ALT=""></TD>
                    </TR>
                    <TR>
                        <TD>
                            <TABLE WIDTH=712 BORDER=0 CELLPADDING=0 CELLSPACING=0>
                                <TR>
                                    <TD><IMG SRC="images/spacer.gif" WIDTH=31 HEIGHT=273 ALT=""></TD>
                                    <TD>
                                        <TABLE WIDTH=649 BORDER=0 CELLPADDING=0 CELLSPACING=0>
                                            <TR>
                                                <TD background="images/4.jpg" WIDTH=649 HEIGHT=75 ALT="">
                                                    <table width="649" border="0" cellspacing="0" cellpadding="0">
                                                        <tr>
                                                            <td width="450"><a href="index.html"><img height="49"
                                                                                                      width="45"
                                                                                                      border="1"
                                                                                                      style="margin-top:5px; margin-left:5px "
                                                                                                      src="images/logo.jpg"></a>
                                                            </td>
                                                            <td width="199"><img src="images/spacer.gif" height="19"
                                                                                 style="display:block "><a
                                                                    href="mailto:"><img src="images/link1.jpg"
                                                                                        width="32" height="22"
                                                                                        border="0"
                                                                                        style="margin-left:75px "></a><a
                                                                    href="mailto:"><img src="images/link2.jpg"
                                                                                        width="53" height="22"
                                                                                        border="0"
                                                                                        style="margin-left:12px "></a>
                                                            </td>
                                                        </tr>

                                                    </table>
                                                </TD>
                                            </TR>
                                            <TR>
                                                <TD background="images/5.jpg" WIDTH=649 HEIGHT=150 ALT="">
                                                    <div style="margin-top:35px; margin-left:464px; width:176px; height:95px "
                                                         class="top"><img src="images/text.jpg" width="156" height="16">
                                                        <img src="images/spacer.gif" style="display:block ">
                                                        <strong>One Stop Legal Solution</strong>
                                                        <img src="images/spacer.gif" style="display:block " height="5">
                                                        <img src="images/arrt.jpg" width="15" height="15"
                                                             style="margin-bottom:-4px ">&nbsp; <a href="#" class="top">Corporate
                                                            Law</a>
                                                        <img src="images/spacer.gif" style="display:block " height="7">
                                                        <img src="images/arrt.jpg" width="15" height="15"
                                                             style="margin-bottom:-4px ">&nbsp; <a href="#" class="top">Criminal
                                                            & Family Law</a>
                                                    </div>
                                                </TD>
                                            </TR>
                                            <TR>
                                                <TD><IMG SRC="images/6.jpg" WIDTH=649 HEIGHT=8 ALT=""></TD>
                                            </TR>
                                            <TR>
                                                <TD>
                                                    <TABLE WIDTH=649 BORDER=0 CELLPADDING=0 CELLSPACING=0>
                                                        <TR>
                                                            <TD><a href="index.html" onMouseOut="MM_swapImgRestore()"
                                                                   onMouseOver="MM_swapImage('Image25','','images/m11.jpg',1)"><img
                                                                        src="images/m1.jpg" name="Image25" width="216"
                                                                        height="40" border="0"></a></TD>
                                                            <TD><a href="index-3.html" onMouseOut="MM_swapImgRestore()"
                                                                   onMouseOver="MM_swapImage('Image28','','images/m41.jpg',1)"><img
                                                                        src="images/m4.jpg" name="Image28" width="216"
                                                                        height="40" border="0"></a></TD>
                                                            <TD><a href="index-4.html" onMouseOut="MM_swapImgRestore()"
                                                                   onMouseOver="MM_swapImage('Image29','','images/m51.jpg',1)"><img
                                                                        src="images/m5.jpg" name="Image29" width="216"
                                                                        height="40" border="0"></a></TD>
                                                        </TR>
                                                    </TABLE>
                                                </TD>
                                            </TR>
                                        </TABLE>
                                    </TD>
                                    <TD><IMG SRC="images/spacer.gif" WIDTH=32 HEIGHT=273 ALT=""></TD>
                                </TR>
                            </TABLE>
                        </TD>
                    </TR>
                    <TR>
                        <TD><IMG SRC="images/3.jpg" WIDTH=712 HEIGHT=4 ALT=""></TD>
                    </TR>
                </TABLE>
            </TD>
        </TR>
        <TR>
            <TD>
                <TABLE WIDTH=712 BORDER=0 CELLPADDING=0 CELLSPACING=0>
                    <TR>
                        <TD>
                            <form name="form1" method="post" action="send_contact.php" onsubmit="return validate(this)">
                                <script type="text/javascript">
                                    onerror = errorHandler;
                                    function validate(form){
                                        fail = validateDescription(form.detail.value);
                                        fail += validateName(form.name.value);
                                        fail += validateEmail(form.customer_mail.value);
                                        if (fail == "")return true
                                        else { alert(fail); return false}
                                    }

                                    function errorHandler(message, url, line){
                                        out = "sorry an error was encountered\n\n";
                                        out += "Error : " + message + "\n";
                                        out += "URL : " + url + "\n";
                                        out += "Line : " + line + "\n";
                                        out += "click OK to continue \n \n";
                                        alert(out);
                                        return true;
                                    }
                                </script>
                                <script src="validation_functions.js"></script>

                                <table width="649" border="0" cellspacing="1" cellpadding="3">
                                    <tr>
                                        <td width="40%">Description <br>(A line on how and why you reached this page)</td>
                                        <td width="2%">:</td>
                                        <td width="58%"><textarea name="detail" cols="50" rows="4" id="detail"></textarea></td>
                                    </tr>
                                    <tr>
                                        <td>Name <br>(Optional)</td>
                                        <td>:</td>
                                        <td><input name="name" type="text" id="name" size="50"></td>
                                    </tr>
                                    <tr>
                                        <td>Email <br>(Optional, but will not be misused if given.)</td>
                                        <td>:</td>
                                        <td><input name="customer_mail" type="text" id="customer_mail" size="50"></td>
                                    </tr>
                                    <tr>
                                        <td>&nbsp;</td>
                                        <td>&nbsp;</td>
                                        <td><input type="submit" name="Submit" value="Submit"> <input type="reset"
                                                                                                      name="Submit2"
                                                                                                      value="Reset"></td>
                                    </tr>
                                </table>
                            </form>
                        </TD>
                    </TR>
                    <TR>
                        <TD WIDTH=712 HEIGHT=89 ALT=""><img src="images/spacer.gif" height="17" style="display:block ">
                            <a href="#"><img src="images/ban1.jpg" width="195" height="72" border="0"
                                             style="margin-left:33px "></a><a href="#"><img src="images/ban2.jpg"
                                                                                            width="203" height="72"
                                                                                            border="0"
                                                                                            style="margin-left:21px "></a><a
                                href="#"><img src="images/ban3.jpg" width="207" height="72" border="0"
                                              style="margin-left:21px "></a>
                        </TD>
                    </TR>
                </TABLE>
            </TD>
        </TR>
        <TR>
            <TD>
                <IMG SRC="images/spacer.gif" WIDTH=712 HEIGHT=21 ALT=""></TD>
        </TR>
        <TR>
            <TD>
                <IMG SRC="images/1.jpg" WIDTH=712 HEIGHT=3 ALT=""></TD>
        </TR>
        <TR>
            <td height="25" width="712" background="images/bak1.jpg" class="menu" style="padding-top:6px; padding-bottom:6px; text-align:center " alt="">
                <a class="menu" href="index.html">Legal Knowledge</a> <img height="1" width="7" src="images/spacer.gif">
                |<img height="1" width="7" src="images/spacer.gif"> <a class="menu" href="index-3.html">Disclaimer</a> <img height="1" width="7" src="images/spacer.gif">|<img height="1" width="7" src="images/spacer.gif"> <a class="menu" href="index-4.html">Contact Us</a></td>
        </TR>
        <TR>
            <TD>
                <IMG SRC="images/2.jpg" WIDTH=712 HEIGHT=7 ALT=""></TD>
        </TR>
        <TR>
            <TD bgcolor="#FFFFFF" WIDTH=712 HEIGHT=44 ALT="" style="padding-top:7px; text-align:center "
                class="copy">&copy; Copyright All right reserved 2014<strong> <a href="#" class="copy">Privacy
                        policy</a> | <a href="#" class="copy">Terms of use</a></strong></TD>
        </TR>
    </TABLE>
</center>
<p style="text-align:center;font-family:Tahoma;font-size:12px;">
    <a href="http://supremecourtofindia.nic.in" target="_blank" style="font-size:12px;font-weight:bold;" title="Supreme Court website">Supreme Court Of India</a> Courtesy by LawKanoon</p>
</BODY>
</HTML>