<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('LawKanoon '. $this->translate('Legal Solutions'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath('css/style.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap.min.css')) ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery.min.js'))
            ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('js/html5shiv.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('js/validation_functions.js'))
            ->prependFile($this->basePath('js/change_color.js'))
        ; ?>

    </head>
    <body>
      <!--  <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>"><img src="<?php echo $this->basePath('img/zf2-logo.png') ?>" alt="Zend Framework 2"/>&nbsp;<?php echo $this->translate('Skeleton Application') ?></a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a></li>
                    </ul>
                </div>  <!--/.nav-collapse
            </div>
        </nav>-->
        <div class="container">
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p style="text-align:center;font-family:Tahoma;font-size:12px;">
                    <a href="http://supremecourtofindia.nic.in" target="_blank" style="font-size:12px;font-weight:bold;" title="Supreme Court website">Supreme Court Of India</a> Courtesy by LawKanoon</p>
                <TR>
                    <TD bgcolor="#FFFFFF" WIDTH=712 HEIGHT=44 ALT="" style="padding-top:7px; text-align:center "
                        class="copy">&copy; <?php echo $this->escapeHtml('Copyright All right reserved 2015'); ?><strong> <a href="#" class="copy">Privacy
                                policy</a> | <a href="#" class="copy">Terms of use</a></strong></TD>
                </TR>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
